teracy-dev:
  # teracy-dev location specification
  location:
    git: https://github.com/teracyhq/dev.git
    branch: v0.6.0-a2
    sync: true

  # teracy-dev-entry auto update
  entry_location:
    git: https://github.com/teracyhq-incubator/teracy-dev-entry-k8s.git
    branch: develop
    sync: true

  extensions:

    - _id: "entry-0"
      path:
        extension: teracy-dev-essential
      location:
        git: https://github.com/teracyhq-incubator/teracy-dev-essential.git
        branch: develop
      require_version: ">= 0.1.0-SNAPSHOT"
      enabled: true

    - _id: "entry-1"
      path:
        extension: teracy-dev-k8s
      location:
        git: https://github.com/teracyhq-incubator/teracy-dev-k8s.git
        branch: v0.1.0
      require_version: ">= 0.1.0, < 0.2.0"
      enabled: true
