variables:
  node_name_prefix: ${NODE_NAME_PREFIX:-k8s}
  node_hostname_prefix: ${NODE_HOSTNAME_PREFIX:-k8s}


vagrant:
  plugins:
    # install and enable vagrant-hostmanager plugin
    - _id: "essential-0"
      state: installed
      enabled: true


teracy-dev:
  # teracy-dev location specification
  location:
    git:
      remote:
        origin: https://github.com/teracyhq/dev.git
      branch: v0.6.0-a5
    sync: true

  # teracy-dev-entry auto update
  entry_location:
    git:
      remote:
        origin: https://github.com/teracyhq-incubator/teracy-dev-entry-k8s.git
      branch: master
    sync: true

  extensions:
    # use teracy-dev-core v0.4.0
    - _id: "kernel-core"
      location:
        git:
          branch: v0.4.0
      require_version: ">= 0.4.0"

    - _id: "entry-essential"
      path:
        extension: teracy-dev-essential
      location:
        git:
          remote:
            origin: https://github.com/teracyhq-incubator/teracy-dev-essential.git
          branch: v0.1.0
      require_version: ">= 0.1.0"
      enabled: true

    - _id: "entry-certs"
      path:
        extension: teracy-dev-certs
      location:
        git:
          remote:
            origin: https://github.com/teracyhq-incubator/teracy-dev-certs.git
          branch: v0.3.0
      require_version: ">= 0.3.0"
      enabled: true

    - _id: "entry-k8s"
      path:
        extension: teracy-dev-k8s
      location:
        git:
          remote:
            origin: https://github.com/teracyhq-incubator/teracy-dev-k8s.git
          branch: v0.3.0
      require_version: ">= 0.3.0"
      enabled: true


nodes:
  - _id: "0"
    plugins:
      - _id: "entry-hostmanager"
        name: vagrant-hostmanager
        config_key: hostmanager
        enabled: true
        options:
          aliases: # set domain aliases for the master node
            - "%{node_hostname_prefix}.%{node_domain_affix}"

teracy-dev-k8s:
  ansible:
    version: latest
    host_vars:
      ingress_nginx_enabled: "True"
      helm_enabled: "True"
      helm_version: v2.11.0
